{% set name = "rioxarray" %}
{% set version = "0.15.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e5080f3c8a6e6542bfd05065b2a22134d28c727efa47b8ee356b430f99b1a1dd

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.10
    - pip
  run:
    - python >=3.10
    - rasterio >=1.3
    - scipy
    - xarray >=2022.3.0
    - pyproj >=3.3
    - packaging
    - numpy >=1.23
test:
  imports:
    - rioxarray

about:
  home: http://github.com/corteva/rioxarray
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: rasterio xarray extension.
  description: rasterio xarray extension.
  doc_url: https://corteva.github.io/rioxarray
  dev_url: http://github.com/corteva/rioxarray

extra:
  recipe-maintainers:
    - snowman2
