{% set name = "rioxarray" %}
{% set version = "0.0.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bfb34935954e26bb8086abfd5f877810f1ee3acc0b28e649eb621c6c3d692d4d

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python 3
    - pip
  run:
    - python 3
    - rasterio
    - scipy
    - xarray
test:
  imports:
    - rioxarray

about:
  home: http://github.com/corteva/rioxarray
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'rasterio xarray extension.'
  description: 'rasterio xarray extension.'
  doc_url: https://corteva.github.io/rioxarray
  dev_url: http://github.com/corteva/rioxarray

extra:
  recipe-maintainers:
    - snowman2
