{% set name = "rioxarray" %}
{% set version = "0.18.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 62bdef2a1ae8ac1de8cd3e809bfe3c8c5d09d1edc873ef9b1f373d37cf8da02b

build:
  number: 0
  skip: true  # [py<310 and s390x]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv
#  s390x is currently unavailable for rasterio so we will skip this platform for now.
requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - rasterio >=1.3.7
    - scipy
    - xarray >=2024.7.0
    - pyproj >=3.3
    - packaging
    - numpy >=1.23
test:
  imports:
    - rioxarray
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/corteva/rioxarray
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: rasterio xarray extension.
  description: |
    rasterio xarray extension.
  doc_url: https://corteva.github.io/rioxarray
  dev_url: https://github.com/corteva/rioxarray

extra:
  recipe-maintainers:
    - snowman2
