{% set name = "rioxarray" %}
{% set version = "0.22.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/corteva/{{ name }}/archive/refs/tags/{{ version}}.tar.gz
  sha256: 104bd13d69475b8a7303ed90d9a2ca4000aba154f916dce4d6b9bbe778edd5e5

build:
  number: 0
  skip: true  # [py<312]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv
requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - packaging
    - rasterio >=1.4.3
    - xarray >=2026.2
    - pyproj >=3.3
    - numpy >=2
test:
  imports:
    - rioxarray
  source_files:
    - test/
  commands:
    - pip check
    # Integration tests under test/integration/ hit real files (GeoTIFF, NetCDF, HDF, MODIS,
    # etc.) and assume a GDAL/rasterio/xarray/PROJ which is quite hard to match versions
    # since not specified by upstream.
    - pytest -v test/unit/
  requires:
    - pip
    - pytest >=3.6

about:
  home: https://corteva.github.io/rioxarray
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: geospatial xarray extension powered by rasterio
  description: |
    rasterio xarray extension.
  doc_url: https://corteva.github.io/rioxarray
  dev_url: https://github.com/corteva/rioxarray

extra:
  recipe-maintainers:
    - snowman2
