travis:
  secure:
    BINSTAR_TOKEN: QeH06csxpRWkd+44EIn3YXAL4Ze/m/CIFvdwcyQd/TMVELVw+J9C1/rdV0CII4cMBIgopnOaAEGKiGZSfV3VwVQFR1gWCC+BEGaZVdd4+lU1/6D42zkyUXMCXdMAcH+jhVSscpDqu+B9jEG7xQM5zXeXF8jt/xb8d+Zy/XE+LS6sMFNco0Z+Nwp7tVHOjr7gdBmBe6vxEPzeaU7WIp44kh7kh6Q3d+YhRPKFks/frEJJCVDd2mcTRfRRqpPAyvznFhXIoLBkCkMA+9rL4YUodV8jq3KWipgPjWIKhZHs85lESyZs/VP18h72Mh7HoVbR+r77twfFMzkFgW6nKuX2+8miePz52P5NI54uDdSXaxBOXbD+6SS1nyAUXLW4seA2R2A16EgUFwSTs5+gcaaQMr79Xy+Chszbu6m1lltZrMeOc9ccQFBnSQ8KBAb//sC+eDKeoD06fGGOUcuJMH2gp0Y6p2XowS91vTCD4dHW2fTaJhmmrKUS3ITS3ndATkonpjoqC43JrtHFH7hLO6t8JdXc30QXa4qP9YBY4g9UYCMpvtwF5g5eXMQ0KwWpF8+FCO7Sm5b4jv/JPgofzT8vqHp+fozyZgrZRJAojb1mr8vSv7W2H/JhrQMKgIpOLn/uz+sfmpWmsR2Abb7bv/oO3wEEzR1D33l6d4TiGnJoXxA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
